# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/mepethree.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Meepeetri(object):
    def setupUi(self, Meepeetri):
        Meepeetri.setObjectName("Meepeetri")
        Meepeetri.resize(579, 405)
        self.centralwidget = QtWidgets.QWidget(Meepeetri)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 1, 1, 1)
        self.song_title = QtWidgets.QLineEdit(self.centralwidget)
        self.song_title.setObjectName("song_title")
        self.gridLayout_2.addWidget(self.song_title, 4, 1, 1, 1)
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setObjectName("add_button")
        self.gridLayout_2.addWidget(self.add_button, 1, 2, 1, 1)
        self.video_url = QtWidgets.QLineEdit(self.centralwidget)
        self.video_url.setObjectName("video_url")
        self.gridLayout_2.addWidget(self.video_url, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.song_album = QtWidgets.QLineEdit(self.centralwidget)
        self.song_album.setObjectName("song_album")
        self.gridLayout_2.addWidget(self.song_album, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 2, 1, 1)
        self.song_artist = QtWidgets.QLineEdit(self.centralwidget)
        self.song_artist.setObjectName("song_artist")
        self.gridLayout_2.addWidget(self.song_artist, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 8, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.embed_thumbnail = QtWidgets.QCheckBox(self.centralwidget)
        self.embed_thumbnail.setObjectName("embed_thumbnail")
        self.gridLayout_2.addWidget(self.embed_thumbnail, 7, 0, 1, 1)
        self.embed_lyrics = QtWidgets.QCheckBox(self.centralwidget)
        self.embed_lyrics.setObjectName("embed_lyrics")
        self.gridLayout_2.addWidget(self.embed_lyrics, 7, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 5, 0, 1, 3)
        self.tasks = QtWidgets.QListWidget(self.centralwidget)
        self.tasks.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tasks.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tasks.setObjectName("tasks")
        self.gridLayout_2.addWidget(self.tasks, 10, 0, 1, 4)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        Meepeetri.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Meepeetri)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 579, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Meepeetri.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Meepeetri)
        self.statusbar.setObjectName("statusbar")
        Meepeetri.setStatusBar(self.statusbar)
        self.action_about = QtWidgets.QAction(Meepeetri)
        self.action_about.setObjectName("action_about")
        self.action_source_code = QtWidgets.QAction(Meepeetri)
        self.action_source_code.setObjectName("action_source_code")
        self.action_save_tasks = QtWidgets.QAction(Meepeetri)
        self.action_save_tasks.setObjectName("action_save_tasks")
        self.action_open_tasks = QtWidgets.QAction(Meepeetri)
        self.action_open_tasks.setObjectName("action_open_tasks")
        self.action_exit = QtWidgets.QAction(Meepeetri)
        self.action_exit.setObjectName("action_exit")
        self.menuFile.addAction(self.action_open_tasks)
        self.menuFile.addAction(self.action_save_tasks)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_exit)
        self.menuHelp.addAction(self.action_about)
        self.menuHelp.addAction(self.action_source_code)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Meepeetri)
        QtCore.QMetaObject.connectSlotsByName(Meepeetri)
        Meepeetri.setTabOrder(self.video_url, self.song_artist)
        Meepeetri.setTabOrder(self.song_artist, self.song_title)
        Meepeetri.setTabOrder(self.song_title, self.song_album)
        Meepeetri.setTabOrder(self.song_album, self.embed_thumbnail)
        Meepeetri.setTabOrder(self.embed_thumbnail, self.embed_lyrics)
        Meepeetri.setTabOrder(self.embed_lyrics, self.add_button)
        Meepeetri.setTabOrder(self.add_button, self.tasks)

    def retranslateUi(self, Meepeetri):
        _translate = QtCore.QCoreApplication.translate
        Meepeetri.setWindowTitle(_translate("Meepeetri", "MainWindow"))
        self.label.setText(_translate("Meepeetri", "Tasks:"))
        self.label_3.setText(_translate("Meepeetri", "Artist Name:"))
        self.label_4.setText(_translate("Meepeetri", "Title:"))
        self.song_title.setPlaceholderText(_translate("Meepeetri", "Welcome To The Machine"))
        self.add_button.setText(_translate("Meepeetri", "Add"))
        self.video_url.setPlaceholderText(_translate("Meepeetri", "https://www.youtube.com/watch?v=lt-udg9zQSE"))
        self.label_2.setText(_translate("Meepeetri", "YouTube Video URL:"))
        self.song_album.setPlaceholderText(_translate("Meepeetri", "Wish You Were Here"))
        self.label_5.setText(_translate("Meepeetri", "Album:"))
        self.song_artist.setPlaceholderText(_translate("Meepeetri", "Pink Floyd"))
        self.label_6.setText(_translate("Meepeetri", "Additional:"))
        self.embed_thumbnail.setText(_translate("Meepeetri", "Embed thumbnail"))
        self.embed_lyrics.setText(_translate("Meepeetri", "Embed lyrics"))
        self.menuFile.setTitle(_translate("Meepeetri", "Fi&le"))
        self.menuHelp.setTitle(_translate("Meepeetri", "Help"))
        self.action_about.setText(_translate("Meepeetri", "&About"))
        self.action_source_code.setText(_translate("Meepeetri", "&Source Code"))
        self.action_source_code.setToolTip(_translate("Meepeetri", "Source Code on Github"))
        self.action_save_tasks.setText(_translate("Meepeetri", "&Save Tasks"))
        self.action_open_tasks.setText(_translate("Meepeetri", "&Open Tasks"))
        self.action_exit.setText(_translate("Meepeetri", "&Quit"))

